FROM node:14.15-slim

WORKDIR /opt/twitter-clone

COPY . .

ENV ACCESS_TOKEN_SECRET=sadcfnamca
ENV REFRESH_TOKEN_SECRET=asdcfamc

ENV AWS_ID=afdlşmöbvds
ENV AWS_SECRET=asdcfamc
ENV AWS_BUCKET_NAME=twitter-clone-images
ENV PASSWORD_HASH=akfmsdşfafmasi

# ENV PORT=3000 or ENV PORT 3000
ENV PORT 3000

RUN npm install

CMD [ "npm", "start" ]
